name: Build & Deploy Docker image to ECR
on: push
jobs:
    build_docker_image_to_ecr:
        name: build_docker_image_to_ecr
        runs-on: ubuntu-latest
        permissions:
          id-token: write   # This is required for requesting the JWT
          contents: read    # This is required for actions/checkout
        steps:
          - name: checkout-code
            uses: actions/checkout@v5
            with:
                ref: main
        
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v5.1.0
            with:
                aws-region: us-west-2
                role-to-assume: ${{ secrets.IAM_ROLE_TO_ASSUME }}
                role-session-name: publish-to-ecr
        
          - name: Login to ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2
        
          - name: Build Docker Image & Publish to ECR
            id: build-push-docker-image
            env:
                ECR_REPOSITORY_URL: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPO: github-gists-api
                IMAGE_VERSION: 1.0.0
            run: |
               docker build -t ${{ env.ECR_REPOSITORY_URL }}/github-gists-api:${{ env.IMAGE_VERSION}} .
               docker push ${{ env.ECR_REPOSITORY_URL }}/github-gists-api:${{ env.IMAGE_VERSION}} .
